//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCabService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CabServiceDbEntities : DbContext
    {
        public CabServiceDbEntities()
            : base("name=CabServiceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_BilllingDetail> tbl_BilllingDetail { get; set; }
        public DbSet<tbl_Driver> tbl_Driver { get; set; }
        public DbSet<tbl_LocationCity> tbl_LocationCity { get; set; }
        public DbSet<tbl_Payments> tbl_Payments { get; set; }
        public DbSet<tbl_PaymentType> tbl_PaymentType { get; set; }
        public DbSet<tbl_Pessenger> tbl_Pessenger { get; set; }
        public DbSet<tbl_PessengerPayment> tbl_PessengerPayment { get; set; }
        public DbSet<tbl_SystemUser> tbl_SystemUser { get; set; }
        public DbSet<tbl_TripDetail> tbl_TripDetail { get; set; }
        public DbSet<tbl_TripRequest> tbl_TripRequest { get; set; }
        public DbSet<tbl_Vehicle> tbl_Vehicle { get; set; }
        public DbSet<tbl_VehicleType> tbl_VehicleType { get; set; }
    }
}
