//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCabService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentType
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<bool> ISCardHolder { get; set; }
        public string CardNO { get; set; }
        public Nullable<System.DateTime> CardExpiry { get; set; }
    }
}
