//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCabService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TripDetail
    {
        public int ID { get; set; }
        public Nullable<int> TripRequestID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<System.DateTime> PickTime { get; set; }
        public Nullable<System.DateTime> DropTime { get; set; }
        public Nullable<int> VehicelID { get; set; }
        public string BillType { get; set; }
    }
}
