//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCabService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payments
    {
        public int ID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public Nullable<int> DriveID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentDate { get; set; }
    }
}
