//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCabService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PessengerPayment
    {
        public int PessengerID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
    }
}
