//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCabService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BilllingDetail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string BillingMonth { get; set; }
        public Nullable<int> DriveriD { get; set; }
        public Nullable<decimal> DriverAmount { get; set; }
        public Nullable<decimal> CompanyAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
